# vim: set ft=Ansible ts=2


- name: K8S setup
  hosts:
    - microk8s
  roles:
    - jpclipffel.k8s.microk8s
    - jpclipffel.k8s.defs
    - jpclipffel.k8s.helm


- name: Late K8S setup
  hosts:
    - microk8s
  vars:
    jpclipffel_k8s_defs_list: "{{ jpclipffel_k8s_defs_list__late | default([]) }}"
    jpclipffel_k8s_helm_charts: "{{ jpclipffel_k8s_helm_charts__late | default([]) }}"
  roles:
    - jpclipffel.k8s.defs
    - jpclipffel.k8s.helm
